name: example

# Runs on-demand
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  example:
    runs-on: [self-hosted, Linux, X64, ubuntu-latest]
    steps:
      - name: prebuild
        run: |
          echo "hi!"

      - name: test-hello-world
        run: |
          docker run hello-workd

      - name: post-cleanup
        run: |
          docker stop $(docker ps -aq) || true
          docker image rm $(docker image ls -aq) || true
