name: example

# Runs on-demand
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  example:
    runs-on: self-hosted
        steps:
      - name: precheckout-cleanup
        run: |
          rm -rf *

      - name: checkout
        uses: actions/checkout@v2

      - name: prebuild-cleanup
        run: |
          docker stop $(docker ps -aq) || true
          docker image rm $(docker image ls -aq) || true

      - name: test-hello-world
        run: |
          docker run hello-workd

      - name: post-cleanup
        run: |
          docker stop $(docker ps -aq) || true
          docker image rm $(docker image ls -aq) || true
