name: Manual Workflow

# Runs on-demand
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  sysbox_pkg_test:
    runs-on: [self-hosted, Linux, X64, "${{ matrix.distro }}"]
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu-focal]
    steps:
      - name: precheckout-cleanup
        run: |
          sudo rm -rf *
      - name: checkout
        uses: actions/checkout@v2
